version: '3.8'

services:
  tianyi-sign:
    image: ${DOCKERHUB_USERNAME:-yourusername}/tianyi-docker:latest
    container_name: tianyi-sign
    restart: unless-stopped
    ports:
      - "${HOST_PORT:-5000}:5000"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# 可选：使用本地构建
#  services:
#    tianyi-sign:
#      build: .
#      container_name: tianyi-sign
#      restart: unless-stopped
#      ports:
#        - "5000:5000"
#      volumes:
#        - ./data:/app/data
#        - ./logs:/app/logs
#      environment:
#        - TZ=Asia/Shanghai
